In [1]:
#Theoretical Questions:

In [1]:
#1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance python's capabilities for numerical operations?

#Purpose of Numpy:
#1-Efficient array computations:- Numpy provides the ndarray object which is a fast and memory-efficient
# Multidimensional array used for large datasets. it allaws for efficient computation of numerical operations on these array.

#2-Mathematical Functions:- it include a wide range of mathematical functions, including those for linear algebra, random number all optimized for performance.
#3-Interfacing with C/C++ and Fortran
#4-Foundation for other libraries

#Advantages of Numpy:
#1-Performance:-Numpy arrays are more efficient than python lists for numerical operations
#2-Vectorization:-Numpy allows for vectorized operations where operations can be applied directly to arrays without the need for explicit loops.
#3-Broadcasting:-Numpy broadcasting capability allows operations to be performed on arrays of different shapes
#4-Memory efficient:-Numpy arrays are more memory efficient than standard python lists.

#Enhance python capabilities:
#1-Handling large datasets
#2-Speed
#3-Easy of use

#Overall Numpy significantly enhances python capabilities in numerical computing making it a powerfull tool for data analysis machin learning and scientific research.


In [2]:
#2. Compare and contrast np.mean() and np.average()functions in numpy.when would you use one over the other?

#np.mean():
#Calculates the arithmetic mean along a specified axis of the array.
#The arithmetic mean is the sum of all the elements divided by the number of elements.
#Does not consider any weights for the elements in the array.
#Useful when you only need a straightforward average.

#np.average():
#Calculates the weighted average along a specified axis of the array.
#Allows you to specify weights for each element.
#Useful when you need to account for the relative importance of each value.

In [3]:
#3. Describe the methods for reversing a numpy array along different axes. provide examples for 1D and 2d arrays.

#Reversing a 1D NumPy Array:
#You can use array slicing with the [::-1] syntax to reverse a 1D array.
#example:-
import numpy as np
arr = np.array([6, 1, 4, 2, 18, 9, 3, 4, 2, 8, 11])
reversed_arr = arr[::-1]
print("Reversed Array:", reversed_arr)


Reversed Array: [11  8  2  4  3  9 18  2  4  1  6]


In [4]:
#Reversing a 2D NumPy Array:
#To reverse a 2D array, you can use np.flip() along the desired axis (rows or columns).
#example:-
# Create a sample 2D NumPy array
arr2D = np.array([[11, 12, 13, 11], [21, 22, 23, 24], [31, 32, 33, 34]])

# Reverse the rows (along axis 0)
reversed_rows = np.flip(arr2D, axis=0)
print("Reversed Rows (axis 0):\n", reversed_rows)

# Reverse the columns (along axis 1)
reversed_columns = np.flip(arr2D, axis=1)
print("Reversed Columns (axis 1):\n", reversed_columns)


Reversed Rows (axis 0):
 [[31 32 33 34]
 [21 22 23 24]
 [11 12 13 11]]
Reversed Columns (axis 1):
 [[11 13 12 11]
 [24 23 22 21]
 [34 33 32 31]]


In [5]:
#4- How can you determine the data type of elements in a numpy array? discuss the importance of data types memory management and performance.

#Determining Data Types in NumPy
#In NumPy, you can determine the data type of elements in an array using the dtype attribute. Here are some ways to check the data type:

#Using dtype Attribute:
#The dtype attribute provides information about the data type of a NumPy array.
#Creating Arrays with Defined Data Types:
#You can create an array with a specific data type using the dtype argument in the np.array() function.

#Importance of Data Types
#Memory Efficiency:
#Choosing appropriate data types ensures efficient memory usage.
#Smaller data types (e.g., int8, float16) consume less memory than larger ones 

#Performance Optimization:
#Data types affect arithmetic operations and computational speed.

#Data Integrity and Error Detection:
#Correct data types prevent unintended behavior (e.g., integer overflow)

In [6]:
#5- Define ndarrays in numpy and explain their key features. how do they differ from standard python lists?

#N-Dimensional Arrays (ndarrays):
#An ndarray in NumPy is a table of elements (usually numbers) with the same data type.
#It can have arbitrary dimensions (rank) and is indexed by a tuple of positive integers.

#Key Features:
#Fixed Size: Unlike Python lists, ndarrays have a fixed size at creation. Resizing creates a new array.
#Homogeneous: All elements in an ndarray must be of the same data type.
#Efficient Vectorized Operations: NumPy arrays allow fast and concise operations.
#Memory Efficiency: Elements occupy the same size in memory.

#Differences from Python Lists:
#Lists can grow dynamically; ndarrays have a fixed size.
#Lists can hold different data types; ndarrays enforce homogeneity.
#NumPy arrays are more memory-efficient and optimized for numerical operations.

In [7]:
#6- Analyze the performance benefits of numpy arrays over python lists for large-scale numerical operations.

#Memory Layout:
#Python Lists: Each element in a Python list has its own memory space and type information.
#However, this approach leads to wasted space due to empty slots in the boxes.

#NumPy Arrays: NumPy arrays store data in memory in a continuous fashion, similar to books placed together on a shelf.

#Flexibility vs. Efficiency:
#Python Lists:
#Flexible: You can put any object (of any type) in a Python list without worrying about type errors.
#Less Efficient: The overhead of managing pointers and individual memory spaces can impact performance.
#NumPy Arrays:
#Optimized for Numerical Computations: NumPy arrays are designed for numerical operations, with efficient element-wise operations and mathematical functions.

In [8]:
#7- Compare vstack() and hstack() functions in numpy. provide examples demonstrating their usage and output.

#vstack() (Vertical Stack):
#vstack() stacks arrays vertically (row-wise), combining them into a single array.
#example-
a = np.array([[1], [2], [3]])
b = np.array([[4], [5], [6]])
result = np.vstack((a, b))
print(result)


[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [9]:
#hstack() (Horizontal Stack):
#hstack() stacks arrays horizontally (column-wise), combining them into a single array.
#example-
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
result = np.hstack((a, b))
print(result)


[1 2 3 4 5 6]


In [10]:
#8- Explain the differences between fliplr() and flipud() methods in numpy including their effects on various array dimensions.

#numpy.fliplr():
#This function flips an array horizontally (from left to right).
#It reverses the order of elements in each row while preserving the shape of the array.
#The input array must be at least 2-dimensional for this function to work.

#numpy.flipud():
#This function flips an array vertically (from top to bottom).
#It reverses the order of elements in each column while preserving the rows.
#Similar to fliplr(), the input array must be at least 2-dimensional.

#fliplr() flips horizontally (left to right), while flipud() flips vertically (up to down).

In [11]:
#9- Discuss the functionality of the array_split() method in numpy. how does  it handle uneven splits?

#Function Signature:
#numpy.array_split(ary, indices_or_sections, axis=0)
#array: The array to be split.
#indices_or_sections: Determines the number of splits or the indices where the array should be split.

#Uneven Splits:
#When the array length (l) cannot be evenly divided by the specified number of splits (n), numpy.array_split() handles it gracefully.
#It returns l % n sub-arrays of size l // n + 1 and the remaining sub-arrays of size l // n.

In [12]:
#10- Explain the concepts of vectorzation and broadcasting in numpy. how do they contribute to efficient array operations?

#Vectorization:
#Vectorization is a technique used to perform operations on arrays without using explicit loops.
#Instead of iterating through each element individually, vectorized operations apply the operation to entire arrays at once.
#NumPy provides vectorized functions that operate on entire arrays, such as element-wise addition, multiplication, and other mathematical operations.

#Broadcasting:
#Broadcasting allows NumPy to handle operations between arrays with different shapes.
#When performing arithmetic operations (addition, subtraction, multiplication, etc.) on arrays, broadcasting ensures that arrays with different shapes are compatible.
#The smaller array is “broadcast” across the larger array to make their shapes compatible.

In [13]:
# PRACTICAL QUESTIONS:

In [20]:
#1- Create a 3*3 numpy array with random integers between 1 and 100. then interchange its rows and columns.
import numpy as np

# Create a 3x3 random array with random integers between 1 and 100
array = np.random.randint(1, 100, size=(3, 3))

# Interchange rows and columns
transposed_array = array.T

print("Original array:")
print(array)
print("\nTransposed array (rows and columns interchanged):")
print(transposed_array)



Original array:
[[77 73 91]
 [71 27 62]
 [29 58 78]]

Transposed array (rows and columns interchanged):
[[77 71 29]
 [73 27 58]
 [91 62 78]]


In [13]:
#2- Generate a 1D numpy array with 10 elements. reshape it into a 2*5 array, then into a 5*2 array.

import numpy as np

# Create a 1D array with 10 elements
arr = np.arange(10)

# Reshape to a 2x5 array
arr_2x5 = arr.reshape(2, 5)

# Reshape to a 5x2 array
arr_5x2 = arr_2x5.reshape(5, 2)

print("1D array:")
print(arr)
print("\n2x5 array:")
print(arr_2x5)
print("\n5x2 array:")
print(arr_5x2)


1D array:
[0 1 2 3 4 5 6 7 8 9]

2x5 array:
[[0 1 2 3 4]
 [5 6 7 8 9]]

5x2 array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [16]:
#3- Create a 4*4 numpy array with random float value. add a border of zeros around it, resulting in a 6*6 array.

# Create a 4x4 array with random float values between 0 and 1
original_array = np.random.rand(4, 4)

# Create a 6x6 array with zeros
bordered_array = np.zeros((6, 6))

# Place the original array inside the bordered array
bordered_array[1:5, 1:5] = original_array

print("Original 4x4 array:")
print(original_array)
print("6x6 array with zeros border:")
print(bordered_array)


Original 4x4 array:
[[0.08157984 0.64424908 0.03920528 0.75837321]
 [0.54172336 0.24737171 0.58312021 0.96823448]
 [0.07986358 0.16667358 0.41997385 0.09742813]
 [0.10924795 0.0439287  0.99318524 0.05805459]]
6x6 array with zeros border:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.08157984 0.64424908 0.03920528 0.75837321 0.        ]
 [0.         0.54172336 0.24737171 0.58312021 0.96823448 0.        ]
 [0.         0.07986358 0.16667358 0.41997385 0.09742813 0.        ]
 [0.         0.10924795 0.0439287  0.99318524 0.05805459 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [23]:
#4- Using numpy create an array of integers from 10 to 60 with a step of 5.

# Create the array
array = np.arange(10, 60, 5)
array


array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55])

In [24]:
#5- Create a numpy array of string['python','numpy','pandas']. Apply different case transformations (uppercase, lowercase, title case,etc) to each element.

# Create a NumPy array with the given strings
string_array = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations
uppercase_array = np.char.upper(string_array)
lowercase_array = np.char.lower(string_array)
titlecase_array = np.char.title(string_array)

print("Original array:", string_array)
print("Uppercase array:", uppercase_array)
print("Lowercase array:", lowercase_array)
print("Titlecase array:", titlecase_array)


Original array: ['python' 'numpy' 'pandas']
Uppercase array: ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase array: ['python' 'numpy' 'pandas']
Titlecase array: ['Python' 'Numpy' 'Pandas']


In [30]:
#6- Generate a numpy array of words. Insert a space between each character of even word in the array.

# Example words
words = np.array(["Ajay", "Bijay"])

# Insert space between characters of even words
even_words = words[::1]
even_words_spaced = np.array([" ".join(word) for word in even_words])

print(even_words_spaced)


['A j a y' 'B i j a y']


In [31]:
#7- Create two 2D numpy arrays and perform element_wise addition, subtraction, multiplication, and division.

# Create two 2D arrays
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

# Element-wise addition
addition_result = array1 + array2

# Element-wise subtraction
subtraction_result = array1 - array2

# Element-wise multiplication
multiplication_result = array1 * array2

# Element-wise division
division_result = array1 / array2

print("Array 1:")
print(array1)
print("Array 2:")
print(array2)
print("Addition result:")
print(addition_result)
print("Subtraction result:")
print(subtraction_result)
print("Multiplication result:")
print(multiplication_result)
print("Division result:")
print(division_result)


Array 1:
[[1 2]
 [3 4]]
Array 2:
[[5 6]
 [7 8]]
Addition result:
[[ 6  8]
 [10 12]]
Subtraction result:
[[-4 -4]
 [-4 -4]]
Multiplication result:
[[ 5 12]
 [21 32]]
Division result:
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [34]:
#8- Use numpy to create a 5*5 identity matrix, then extract its diagonal elements.

identity_matrix = np.eye(5)
print("Identity Matrix:")
print(identity_matrix)


Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [33]:
diagonal_elements = np.diag(identity_matrix)
print("Diagonal Elements:")
print(diagonal_elements)


Diagonal Elements:
[1. 1. 1. 1. 1.]


In [37]:
#9- Generate a numpy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

# Generate the array
random_integers = np.random.randint(0, 1000, size=100)

# Function to check if a number is prime
def is_prime(num):
    if num < 2:
        return False
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            return False
    return True

# Filter prime numbers from the array
prime_numbers = [num for num in random_integers if is_prime(num)]

print("Random integers array:")
print(random_integers)
print("\nPrime numbers in the array:")
print(prime_numbers)


Random integers array:
[913 466 579 887 568 321 735 118 286 222 695 818  93 743 715 243 789 266
 422 280 974  77 236 798 893 417 587 580 894 233 828 786 804 798 270 788
 594 443  94 410 317 883 108 907 615 415 685 890 933 951 243 128 844  84
 523 520 607 398 803 951  60 301 973 643 253 402 101 642 198 329 550 154
  92 283 934 426 594   9 976 127 779 860 678 415 309 623  37 576 842 902
 671 403 378 355 305 345 600 172 711 942]

Prime numbers in the array:
[887, 743, 587, 233, 443, 317, 883, 907, 523, 607, 643, 101, 283, 127, 37]


In [51]:
#10- Create a numpy array representing daily temperatures for a month. calculate and display the weekly averages.

daily_tempretures = np.random.randint(10, 30, 30)
print("Daily_tempretures:")
print(daily_tempretures )
weekly_averages = [np.mean(daily_temperatures[i:i+7]) for i in range(0, 30, 7)]
print("\nWeekly averages:")
print(weekly_averages)

Daily_tempretures:
[21 20 28 23 29 15 27 25 16 29 16 19 21 15 27 22 14 29 14 27 27 13 14 23
 19 18 22 18 17 28]

Weekly averages:
[74.42857142857143, 79.42857142857143, 74.57142857142857, 77.0, 81.0]
